### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fabiommendes** [lappis-unb/rouana-bot#1]
# 1.0
* [ ] Integrar Rasa ao rocketchat
* [ ] Definir arquitetura do bot
  - Base de conhecimento
  - Português
  - Histórias
  - Pipeline
* [ ]  Testes A/B no portal

# 2.0
* [ ] Ferramenta GUI para popular a base de dados do Bot
* [ ] Configurar bot multi-contexto
* [ ] Bot SALIC para as telas de submissão
